### ISSUE TITLE
The dataset

### ISSUE THREAD

**Issue by kaijieshi7** [hassony2/obman#12]
Hi, I registered yesterday and only received a email let me wait your contact me.
When will you contact me?
Best
Kaijie

**Comment by kaijieshi7** [comment]
Hello, I want to download the dataset, Can you help me?

**Comment by kaijieshi7** [comment]
Hello?

**Comment by hassony2** [comment]
Hi,

Could you try and fill the form again and check if the information to download the dataset is available in the email you reaceive ?

Have a great day !

Yana

**Comment by kaijieshi7** [comment]
I have try two times, and it does't send me a email to download dataset

**Comment by kaijieshi7** [comment]
![image](https://user-images.githubusercontent.com/19171201/197760092-55b2cfa6-41b3-490c-8f37-d17888ac60be.png)
Only this email

**Comment by jojo23333** [comment]
@kaijieshi7 Hi, I wonder, did you managed to get the dataset?
