### ISSUE TITLE
Hand grasp without object

### ISSUE THREAD

**Issue by Franborat** [hassony2/obman#5]
Hello!

First of all, congratulations for this interesting project. I am a student doing my Master Thesis about Conditional GANs and I find this dataset very interesting. 

I am wondering if there is any way to load an image sample and erase the object, keeping the hand grasp just as if it was holding it. That would allow me to have pairs of images one with and another without the object. 

Thank you!

**Comment by hassony2** [comment]
Hi @Franborat,

These images are also present in the released dataset :) under `obman/train/rgb_hand` for instance for the train set.

Best !

Yana
