### ISSUE TITLE
Email no reply

### ISSUE THREAD

**Issue by www516717402** [hassony2/obman#6]
Hello hassony2, Great data. I already send email by specific about four days, However nobody reply.

**Comment by hassony2** [comment]
Hi @www516717402 ,

Sorry about the delay, you should have received the access now !
Feel free to reopen the issus if you didn't receive the email :)

**Comment by www516717402** [comment]
Great help. Thank you.

**Comment by www516717402** [comment]
@hassony2 Hello, I cant download ObMan dataset (obman.zip), please check it.

**Comment by hassony2** [comment]
@www516717402, could you detail the error you are getting ?

Thanks !
